# Generated by Django 3.0.4 on 2020-03-04 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('ColId', models.AutoField(primary_key=True, serialize=False)),
                ('colourdesc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductTitle', models.CharField(max_length=50)),
                ('Qty', models.PositiveIntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('Img', models.ImageField(upload_to='pics')),
                ('Manufacturer', models.CharField(max_length=50)),
                ('Desc', models.TextField()),
                ('ColId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titanCart.Colour')),
            ],
        ),
    ]
