# Generated by Django 3.0.4 on 2020-03-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanCart', '0002_auto_20200318_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('D', 'Default'), ('EL', 'Electronics'), ('En', 'Entairtnment'), ('H&F', 'Health and Fitness'), ('M', 'Mens Clothes'), ('W', 'Womens Clothes'), ('KC', 'Kids Clothes'), ('SE', 'Security'), ('W', 'Watches'), ('SH', 'Shoes')], default='D', max_length=4),
            preserve_default=False,
        ),
    ]
