# Generated by Django 3.0.4 on 2020-03-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanCart', '0003_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Slug',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
    ]
