# Generated by Django 3.0.4 on 2020-03-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titanCart', '0004_products_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Slug',
            new_name='slug',
        ),
    ]
