# Generated by Django 3.0.4 on 2020-03-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titanCart', '0005_auto_20200319_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ref_code',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
