# Generated by Django 3.0.4 on 2020-03-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanCart', '0010_cart_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='recomended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productIDs', models.ManyToManyField(to='titanCart.Products')),
            ],
        ),
        migrations.CreateModel(
            name='featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productIDs', models.ManyToManyField(to='titanCart.Products')),
            ],
        ),
    ]
