# Generated by Django 3.0.4 on 2020-03-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titanCart', '0012_ordersummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='OrderSummary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='titanCart.OrderSummary'),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='Alt_Phone',
            field=models.CharField(max_length=15),
        ),
    ]
