# Generated by Django 3.0.4 on 2020-04-12 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titanCart', '0016_productreview_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='pTags',
            fields=[
                ('tagId', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
                ('prodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titanCart.Products')),
            ],
        ),
    ]
