# Generated by Django 3.0.4 on 2020-04-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanCart', '0018_searchcriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Delivered',
            field=models.BooleanField(default=False),
        ),
    ]
