# Generated by Django 3.0.4 on 2020-04-20 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('titanCart', '0019_cart_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='Alt_Phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='First_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='Last_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='Shipping_Address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='Shipping_Address_b',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='Shipping_Country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='Shipping_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='Title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='Zip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('SalesId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titanCart.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
